include: package:lint/analysis_options.yaml
analyzer:
  exclude:
    - lib/services/moor/moor_database.g.dart
  errors:
    prefer_single_quotes: error
    missing_required_param: error
    prefer_const_declarations: error
    prefer_const_constructors: error
    exhaustive_cases: error
    argument_type_not_assignable : warning
    avoid_escaping_inner_quotes : info

linter:
  rules:
    prefer_single_quotes: true
    prefer_const_declarations: true
    prefer_const_constructors: true
    exhaustive_cases: true
    always_specify_types: true
    avoid_print: false
    sort_pub_dependencies: false
    directives_ordering: false
    avoid_bool_literals_in_conditional_expressions: false
    use_build_context_synchronously: false
    avoid_escaping_inner_quotes: false
    avoid_dynamic_calls: false
    depend_on_referenced_packages: false

dart_code_metrics:
  anti-patterns:
    - long-method
    - long-parameter-list
  metrics:
    cyclomatic-complexity: 20
    maximum-nesting-level: 5
    number-of-parameters: 4
    source-lines-of-code: 50
  metrics-exclude:
    - test/**
  rules:
    - newline-before-return
    - no-boolean-literal-compare
    - no-empty-block
    - prefer-trailing-comma
    - prefer-conditional-expressions
    - no-equal-then-else